
# @VARS
USERNAME=mohsin
USERPASS=1234
HOST=172.17.0.1
ROOT_USER=root
ROOT_PASSWORD=1234
CONTAINER_NAME='mysql-test'
IMAGE_NAME='mysql/mysql-server'

docker run -d -p 3306:3306 --name ${CONTAINER_NAME} -e MYSQL_ROOT_PASSWORD=${ROOT_PASSWORD} ${IMAGE_NAME}	

# INITIALIZE @VARS IN TERMINAL
docker exec -it ${CONTAINER_NAME} bash -l;

# REINITIALIZE @VARS AGAIN IN TERMINAL
mysql -u${ROOT_USER} -p${ROOT_PASSWORD} <<EOF
DROP USER IF EXISTS '${USERNAME}'@'${HOST}';
CREATE USER '${USERNAME}'@'${HOST}' IDENTIFIED BY '${USERPASS}'; 
GRANT ALL ON *.* TO '${USERNAME}'@'${HOST}'; 
FLUSH PRIVILEGES;
SELECT user, host FROM mysql.user;
EOF

# GET USERS FROM MYSQL
mysql -u${ROOT_USER} -p${ROOT_PASSWORD} <<EOF
SELECT user, host FROM mysql.user;
EOF

# DROP MY USER
mysql -u${ROOT_USER} -p${ROOT_PASSWORD} <<EOF
DROP USER IF EXISTS '${USERNAME}'@'${HOST}';
EOF
